/********************************************************************************
** Form generated from reading UI file 'newg.ui'
**
** Created: Fri May 15 23:17:22 2015
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_NEWG_H
#define UI_NEWG_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QGridLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QTabWidget>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QWidget *gridLayoutWidget;
    QGridLayout *gridLayout_3;
    QTabWidget *verticalTabWidget;
    QWidget *verticalTabWidgetPage1;
    QTabWidget *tabWidget;
    QWidget *danrenjian;
    QPushButton *drj_2;
    QPushButton *drj_3;
    QPushButton *drj_5;
    QPushButton *drj_6;
    QPushButton *drj_7;
    QPushButton *drj_8;
    QPushButton *drj_9;
    QPushButton *drj_1;
    QPushButton *drj_4;
    QPushButton *drj_10;
    QLabel *label;
    QWidget *shuangrenjian;
    QPushButton *srj_1;
    QPushButton *srj_2;
    QPushButton *srj_3;
    QPushButton *srj_4;
    QPushButton *srj_6;
    QPushButton *srj_7;
    QPushButton *srj_8;
    QPushButton *srj_5;
    QPushButton *srj_10;
    QPushButton *srj_9;
    QLabel *label_2;
    QWidget *haohuajian;
    QPushButton *hhj_1;
    QPushButton *hhj_2;
    QPushButton *hhj_3;
    QPushButton *hhj_4;
    QPushButton *hhj_5;
    QPushButton *hhj_6;
    QPushButton *hhj_7;
    QPushButton *pushButton_8;
    QLabel *label_3;
    QWidget *haohuataofang;
    QPushButton *hht_1;
    QPushButton *hht_2;
    QPushButton *hht_3;
    QPushButton *hht_4;
    QPushButton *hht_5;
    QPushButton *hht_6;
    QLabel *label_4;
    QWidget *verticalTabWidgetPage2;
    QTabWidget *tabWidget_2;
    QWidget *danrenjian_2;
    QPushButton *drj_11;
    QPushButton *drj_12;
    QPushButton *drj_13;
    QPushButton *drj_14;
    QPushButton *drj_15;
    QPushButton *drj_16;
    QPushButton *drj_17;
    QPushButton *drj_18;
    QPushButton *drj_19;
    QPushButton *drj_20;
    QLabel *label_5;
    QWidget *shuangrenjian_2;
    QPushButton *srj_11;
    QPushButton *srj_12;
    QPushButton *srj_13;
    QPushButton *srj_14;
    QPushButton *srj_15;
    QPushButton *srj_16;
    QPushButton *srj_17;
    QPushButton *srj_18;
    QPushButton *srj_19;
    QPushButton *srj_20;
    QLabel *label_6;
    QWidget *haohuajian_2;
    QPushButton *hhj_8;
    QPushButton *hhj_9;
    QPushButton *hhj_10;
    QPushButton *hhj_11;
    QPushButton *hhj_12;
    QPushButton *hhj_13;
    QPushButton *hhj_14;
    QPushButton *pushButton_9;
    QLabel *label_7;
    QWidget *haohuataofang_2;
    QPushButton *hht_7;
    QPushButton *hht_8;
    QPushButton *hht_9;
    QPushButton *hht_10;
    QPushButton *hht_11;
    QPushButton *hht_12;
    QLabel *label_8;
    QWidget *verticalTabWidgetPage3;
    QTabWidget *tabWidget_3;
    QWidget *danrenjian_3;
    QPushButton *drj_21;
    QPushButton *drj_22;
    QPushButton *drj_23;
    QPushButton *drj_24;
    QPushButton *drj_25;
    QPushButton *drj_26;
    QPushButton *drj_27;
    QPushButton *drj_28;
    QPushButton *drj_29;
    QPushButton *drj_30;
    QLabel *label_9;
    QWidget *shuangrenjian_3;
    QPushButton *srj_21;
    QPushButton *srj_22;
    QPushButton *srj_23;
    QPushButton *srj_24;
    QPushButton *srj_25;
    QPushButton *srj_26;
    QPushButton *srj_27;
    QPushButton *srj_28;
    QPushButton *srj_29;
    QPushButton *srj_30;
    QLabel *label_10;
    QWidget *haohuajian_3;
    QPushButton *hhj_15;
    QPushButton *hhj_16;
    QPushButton *hhj_17;
    QPushButton *hhj_18;
    QPushButton *hhj_19;
    QPushButton *hhj_20;
    QPushButton *hhj_21;
    QPushButton *pushButton_10;
    QLabel *label_11;
    QWidget *haohuataofang_3;
    QPushButton *hht_13;
    QPushButton *hht_14;
    QPushButton *hht_15;
    QPushButton *hht_16;
    QPushButton *hht_17;
    QPushButton *hht_18;
    QLabel *label_12;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QString::fromUtf8("Dialog"));
        Dialog->setEnabled(true);
        Dialog->resize(737, 523);
        Dialog->setMouseTracking(false);
        Dialog->setAcceptDrops(false);
        Dialog->setLayoutDirection(Qt::LeftToRight);
        Dialog->setAutoFillBackground(false);
        Dialog->setModal(false);
        gridLayoutWidget = new QWidget(Dialog);
        gridLayoutWidget->setObjectName(QString::fromUtf8("gridLayoutWidget"));
        gridLayoutWidget->setGeometry(QRect(0, 0, 731, 521));
        gridLayout_3 = new QGridLayout(gridLayoutWidget);
        gridLayout_3->setObjectName(QString::fromUtf8("gridLayout_3"));
        gridLayout_3->setContentsMargins(0, 0, 0, 0);
        verticalTabWidget = new QTabWidget(gridLayoutWidget);
        verticalTabWidget->setObjectName(QString::fromUtf8("verticalTabWidget"));
        QFont font;
        font.setFamily(QString::fromUtf8("SimSun-ExtB"));
        font.setPointSize(16);
        font.setBold(true);
        font.setWeight(75);
        verticalTabWidget->setFont(font);
        verticalTabWidget->setTabPosition(QTabWidget::West);
        verticalTabWidgetPage1 = new QWidget();
        verticalTabWidgetPage1->setObjectName(QString::fromUtf8("verticalTabWidgetPage1"));
        tabWidget = new QTabWidget(verticalTabWidgetPage1);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(1, 1, 729, 519));
        tabWidget->setFont(font);
        tabWidget->setStyleSheet(QString::fromUtf8(""));
        tabWidget->setTabPosition(QTabWidget::North);
        tabWidget->setTabShape(QTabWidget::Rounded);
        tabWidget->setElideMode(Qt::ElideNone);
        danrenjian = new QWidget();
        danrenjian->setObjectName(QString::fromUtf8("danrenjian"));
        drj_2 = new QPushButton(danrenjian);
        drj_2->setObjectName(QString::fromUtf8("drj_2"));
        drj_2->setGeometry(QRect(450, 20, 120, 60));
        QFont font1;
        font1.setPointSize(30);
        drj_2->setFont(font1);
        drj_3 = new QPushButton(danrenjian);
        drj_3->setObjectName(QString::fromUtf8("drj_3"));
        drj_3->setGeometry(QRect(100, 100, 120, 60));
        drj_3->setFont(font1);
        drj_5 = new QPushButton(danrenjian);
        drj_5->setObjectName(QString::fromUtf8("drj_5"));
        drj_5->setGeometry(QRect(100, 180, 120, 60));
        drj_5->setFont(font1);
        drj_6 = new QPushButton(danrenjian);
        drj_6->setObjectName(QString::fromUtf8("drj_6"));
        drj_6->setGeometry(QRect(450, 180, 120, 60));
        drj_6->setFont(font1);
        drj_7 = new QPushButton(danrenjian);
        drj_7->setObjectName(QString::fromUtf8("drj_7"));
        drj_7->setGeometry(QRect(100, 260, 120, 60));
        drj_7->setFont(font1);
        drj_8 = new QPushButton(danrenjian);
        drj_8->setObjectName(QString::fromUtf8("drj_8"));
        drj_8->setGeometry(QRect(450, 260, 120, 60));
        drj_8->setFont(font1);
        drj_9 = new QPushButton(danrenjian);
        drj_9->setObjectName(QString::fromUtf8("drj_9"));
        drj_9->setGeometry(QRect(100, 340, 120, 60));
        drj_9->setFont(font1);
        drj_1 = new QPushButton(danrenjian);
        drj_1->setObjectName(QString::fromUtf8("drj_1"));
        drj_1->setGeometry(QRect(100, 20, 120, 60));
        QFont font2;
        font2.setPointSize(30);
        font2.setItalic(false);
        drj_1->setFont(font2);
        drj_4 = new QPushButton(danrenjian);
        drj_4->setObjectName(QString::fromUtf8("drj_4"));
        drj_4->setGeometry(QRect(450, 100, 120, 60));
        drj_4->setFont(font1);
        drj_10 = new QPushButton(danrenjian);
        drj_10->setObjectName(QString::fromUtf8("drj_10"));
        drj_10->setGeometry(QRect(450, 340, 120, 60));
        drj_10->setFont(font1);
        label = new QLabel(danrenjian);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(0, 0, 721, 481));
        label->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget->addTab(danrenjian, QString());
        label->raise();
        drj_2->raise();
        drj_3->raise();
        drj_5->raise();
        drj_6->raise();
        drj_7->raise();
        drj_8->raise();
        drj_9->raise();
        drj_1->raise();
        drj_4->raise();
        drj_10->raise();
        shuangrenjian = new QWidget();
        shuangrenjian->setObjectName(QString::fromUtf8("shuangrenjian"));
        srj_1 = new QPushButton(shuangrenjian);
        srj_1->setObjectName(QString::fromUtf8("srj_1"));
        srj_1->setGeometry(QRect(100, 20, 121, 61));
        srj_1->setFont(font1);
        srj_2 = new QPushButton(shuangrenjian);
        srj_2->setObjectName(QString::fromUtf8("srj_2"));
        srj_2->setGeometry(QRect(450, 20, 121, 61));
        srj_2->setFont(font1);
        srj_3 = new QPushButton(shuangrenjian);
        srj_3->setObjectName(QString::fromUtf8("srj_3"));
        srj_3->setGeometry(QRect(100, 100, 121, 61));
        srj_3->setFont(font1);
        srj_4 = new QPushButton(shuangrenjian);
        srj_4->setObjectName(QString::fromUtf8("srj_4"));
        srj_4->setGeometry(QRect(450, 100, 121, 61));
        srj_4->setFont(font1);
        srj_6 = new QPushButton(shuangrenjian);
        srj_6->setObjectName(QString::fromUtf8("srj_6"));
        srj_6->setGeometry(QRect(450, 180, 121, 61));
        srj_6->setFont(font1);
        srj_7 = new QPushButton(shuangrenjian);
        srj_7->setObjectName(QString::fromUtf8("srj_7"));
        srj_7->setGeometry(QRect(100, 260, 121, 61));
        srj_7->setFont(font1);
        srj_8 = new QPushButton(shuangrenjian);
        srj_8->setObjectName(QString::fromUtf8("srj_8"));
        srj_8->setGeometry(QRect(450, 260, 121, 61));
        srj_8->setFont(font1);
        srj_5 = new QPushButton(shuangrenjian);
        srj_5->setObjectName(QString::fromUtf8("srj_5"));
        srj_5->setGeometry(QRect(100, 180, 121, 61));
        srj_5->setFont(font1);
        srj_10 = new QPushButton(shuangrenjian);
        srj_10->setObjectName(QString::fromUtf8("srj_10"));
        srj_10->setGeometry(QRect(450, 340, 121, 61));
        srj_10->setFont(font1);
        srj_9 = new QPushButton(shuangrenjian);
        srj_9->setObjectName(QString::fromUtf8("srj_9"));
        srj_9->setGeometry(QRect(100, 340, 121, 61));
        srj_9->setFont(font1);
        label_2 = new QLabel(shuangrenjian);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(0, 0, 721, 481));
        label_2->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget->addTab(shuangrenjian, QString());
        label_2->raise();
        srj_1->raise();
        srj_2->raise();
        srj_3->raise();
        srj_4->raise();
        srj_6->raise();
        srj_7->raise();
        srj_8->raise();
        srj_5->raise();
        srj_10->raise();
        srj_9->raise();
        haohuajian = new QWidget();
        haohuajian->setObjectName(QString::fromUtf8("haohuajian"));
        hhj_1 = new QPushButton(haohuajian);
        hhj_1->setObjectName(QString::fromUtf8("hhj_1"));
        hhj_1->setGeometry(QRect(100, 20, 121, 61));
        hhj_1->setFont(font1);
        hhj_2 = new QPushButton(haohuajian);
        hhj_2->setObjectName(QString::fromUtf8("hhj_2"));
        hhj_2->setGeometry(QRect(450, 20, 121, 61));
        hhj_2->setFont(font1);
        hhj_3 = new QPushButton(haohuajian);
        hhj_3->setObjectName(QString::fromUtf8("hhj_3"));
        hhj_3->setGeometry(QRect(100, 100, 121, 61));
        hhj_3->setFont(font1);
        hhj_4 = new QPushButton(haohuajian);
        hhj_4->setObjectName(QString::fromUtf8("hhj_4"));
        hhj_4->setGeometry(QRect(450, 100, 121, 61));
        hhj_4->setFont(font1);
        hhj_5 = new QPushButton(haohuajian);
        hhj_5->setObjectName(QString::fromUtf8("hhj_5"));
        hhj_5->setGeometry(QRect(100, 180, 121, 61));
        hhj_5->setFont(font1);
        hhj_6 = new QPushButton(haohuajian);
        hhj_6->setObjectName(QString::fromUtf8("hhj_6"));
        hhj_6->setGeometry(QRect(450, 180, 121, 61));
        hhj_6->setFont(font1);
        hhj_7 = new QPushButton(haohuajian);
        hhj_7->setObjectName(QString::fromUtf8("hhj_7"));
        hhj_7->setGeometry(QRect(100, 260, 121, 61));
        hhj_7->setFont(font1);
        pushButton_8 = new QPushButton(haohuajian);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(450, 260, 121, 61));
        pushButton_8->setFont(font1);
        label_3 = new QLabel(haohuajian);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(1, 1, 721, 481));
        label_3->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget->addTab(haohuajian, QString());
        label_3->raise();
        hhj_1->raise();
        hhj_2->raise();
        hhj_3->raise();
        hhj_4->raise();
        hhj_5->raise();
        hhj_6->raise();
        hhj_7->raise();
        pushButton_8->raise();
        haohuataofang = new QWidget();
        haohuataofang->setObjectName(QString::fromUtf8("haohuataofang"));
        hht_1 = new QPushButton(haohuataofang);
        hht_1->setObjectName(QString::fromUtf8("hht_1"));
        hht_1->setGeometry(QRect(100, 20, 121, 61));
        hht_1->setFont(font1);
        hht_2 = new QPushButton(haohuataofang);
        hht_2->setObjectName(QString::fromUtf8("hht_2"));
        hht_2->setGeometry(QRect(450, 20, 121, 61));
        hht_2->setFont(font1);
        hht_3 = new QPushButton(haohuataofang);
        hht_3->setObjectName(QString::fromUtf8("hht_3"));
        hht_3->setGeometry(QRect(100, 100, 121, 61));
        hht_3->setFont(font1);
        hht_4 = new QPushButton(haohuataofang);
        hht_4->setObjectName(QString::fromUtf8("hht_4"));
        hht_4->setGeometry(QRect(450, 100, 121, 61));
        hht_4->setFont(font1);
        hht_5 = new QPushButton(haohuataofang);
        hht_5->setObjectName(QString::fromUtf8("hht_5"));
        hht_5->setGeometry(QRect(100, 180, 121, 61));
        hht_5->setFont(font1);
        hht_6 = new QPushButton(haohuataofang);
        hht_6->setObjectName(QString::fromUtf8("hht_6"));
        hht_6->setGeometry(QRect(450, 180, 121, 61));
        hht_6->setFont(font1);
        label_4 = new QLabel(haohuataofang);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(0, 0, 721, 481));
        label_4->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget->addTab(haohuataofang, QString());
        label_4->raise();
        hht_1->raise();
        hht_2->raise();
        hht_3->raise();
        hht_4->raise();
        hht_5->raise();
        hht_6->raise();
        verticalTabWidget->addTab(verticalTabWidgetPage1, QString());
        verticalTabWidgetPage2 = new QWidget();
        verticalTabWidgetPage2->setObjectName(QString::fromUtf8("verticalTabWidgetPage2"));
        tabWidget_2 = new QTabWidget(verticalTabWidgetPage2);
        tabWidget_2->setObjectName(QString::fromUtf8("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(1, 1, 729, 519));
        QFont font3;
        font3.setPointSize(16);
        tabWidget_2->setFont(font3);
        tabWidget_2->setStyleSheet(QString::fromUtf8(""));
        tabWidget_2->setTabPosition(QTabWidget::North);
        tabWidget_2->setTabShape(QTabWidget::Rounded);
        tabWidget_2->setElideMode(Qt::ElideNone);
        danrenjian_2 = new QWidget();
        danrenjian_2->setObjectName(QString::fromUtf8("danrenjian_2"));
        drj_11 = new QPushButton(danrenjian_2);
        drj_11->setObjectName(QString::fromUtf8("drj_11"));
        drj_11->setGeometry(QRect(450, 20, 120, 60));
        drj_11->setFont(font1);
        drj_12 = new QPushButton(danrenjian_2);
        drj_12->setObjectName(QString::fromUtf8("drj_12"));
        drj_12->setGeometry(QRect(100, 100, 120, 60));
        drj_12->setFont(font1);
        drj_13 = new QPushButton(danrenjian_2);
        drj_13->setObjectName(QString::fromUtf8("drj_13"));
        drj_13->setGeometry(QRect(100, 180, 120, 60));
        drj_13->setFont(font1);
        drj_14 = new QPushButton(danrenjian_2);
        drj_14->setObjectName(QString::fromUtf8("drj_14"));
        drj_14->setGeometry(QRect(450, 180, 120, 60));
        drj_14->setFont(font1);
        drj_15 = new QPushButton(danrenjian_2);
        drj_15->setObjectName(QString::fromUtf8("drj_15"));
        drj_15->setGeometry(QRect(100, 260, 120, 60));
        drj_15->setFont(font1);
        drj_16 = new QPushButton(danrenjian_2);
        drj_16->setObjectName(QString::fromUtf8("drj_16"));
        drj_16->setGeometry(QRect(450, 260, 120, 60));
        drj_16->setFont(font1);
        drj_17 = new QPushButton(danrenjian_2);
        drj_17->setObjectName(QString::fromUtf8("drj_17"));
        drj_17->setGeometry(QRect(100, 340, 120, 60));
        drj_17->setFont(font1);
        drj_18 = new QPushButton(danrenjian_2);
        drj_18->setObjectName(QString::fromUtf8("drj_18"));
        drj_18->setGeometry(QRect(100, 20, 120, 60));
        drj_18->setFont(font2);
        drj_19 = new QPushButton(danrenjian_2);
        drj_19->setObjectName(QString::fromUtf8("drj_19"));
        drj_19->setGeometry(QRect(450, 100, 120, 60));
        drj_19->setFont(font1);
        drj_20 = new QPushButton(danrenjian_2);
        drj_20->setObjectName(QString::fromUtf8("drj_20"));
        drj_20->setGeometry(QRect(450, 340, 120, 60));
        drj_20->setFont(font1);
        label_5 = new QLabel(danrenjian_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(0, 0, 721, 481));
        label_5->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget_2->addTab(danrenjian_2, QString());
        label_5->raise();
        drj_11->raise();
        drj_12->raise();
        drj_13->raise();
        drj_14->raise();
        drj_15->raise();
        drj_16->raise();
        drj_17->raise();
        drj_18->raise();
        drj_19->raise();
        drj_20->raise();
        shuangrenjian_2 = new QWidget();
        shuangrenjian_2->setObjectName(QString::fromUtf8("shuangrenjian_2"));
        srj_11 = new QPushButton(shuangrenjian_2);
        srj_11->setObjectName(QString::fromUtf8("srj_11"));
        srj_11->setGeometry(QRect(100, 20, 121, 61));
        srj_11->setFont(font1);
        srj_12 = new QPushButton(shuangrenjian_2);
        srj_12->setObjectName(QString::fromUtf8("srj_12"));
        srj_12->setGeometry(QRect(450, 20, 121, 61));
        srj_12->setFont(font1);
        srj_13 = new QPushButton(shuangrenjian_2);
        srj_13->setObjectName(QString::fromUtf8("srj_13"));
        srj_13->setGeometry(QRect(100, 100, 121, 61));
        srj_13->setFont(font1);
        srj_14 = new QPushButton(shuangrenjian_2);
        srj_14->setObjectName(QString::fromUtf8("srj_14"));
        srj_14->setGeometry(QRect(450, 100, 121, 61));
        srj_14->setFont(font1);
        srj_15 = new QPushButton(shuangrenjian_2);
        srj_15->setObjectName(QString::fromUtf8("srj_15"));
        srj_15->setGeometry(QRect(450, 180, 121, 61));
        srj_15->setFont(font1);
        srj_16 = new QPushButton(shuangrenjian_2);
        srj_16->setObjectName(QString::fromUtf8("srj_16"));
        srj_16->setGeometry(QRect(100, 260, 121, 61));
        srj_16->setFont(font1);
        srj_17 = new QPushButton(shuangrenjian_2);
        srj_17->setObjectName(QString::fromUtf8("srj_17"));
        srj_17->setGeometry(QRect(450, 260, 121, 61));
        srj_17->setFont(font1);
        srj_18 = new QPushButton(shuangrenjian_2);
        srj_18->setObjectName(QString::fromUtf8("srj_18"));
        srj_18->setGeometry(QRect(100, 180, 121, 61));
        srj_18->setFont(font1);
        srj_19 = new QPushButton(shuangrenjian_2);
        srj_19->setObjectName(QString::fromUtf8("srj_19"));
        srj_19->setGeometry(QRect(450, 340, 121, 61));
        srj_19->setFont(font1);
        srj_20 = new QPushButton(shuangrenjian_2);
        srj_20->setObjectName(QString::fromUtf8("srj_20"));
        srj_20->setGeometry(QRect(100, 340, 121, 61));
        srj_20->setFont(font1);
        label_6 = new QLabel(shuangrenjian_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(0, 0, 721, 481));
        label_6->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget_2->addTab(shuangrenjian_2, QString());
        label_6->raise();
        srj_11->raise();
        srj_12->raise();
        srj_13->raise();
        srj_14->raise();
        srj_15->raise();
        srj_16->raise();
        srj_17->raise();
        srj_18->raise();
        srj_19->raise();
        srj_20->raise();
        haohuajian_2 = new QWidget();
        haohuajian_2->setObjectName(QString::fromUtf8("haohuajian_2"));
        hhj_8 = new QPushButton(haohuajian_2);
        hhj_8->setObjectName(QString::fromUtf8("hhj_8"));
        hhj_8->setGeometry(QRect(100, 20, 121, 61));
        hhj_8->setFont(font1);
        hhj_9 = new QPushButton(haohuajian_2);
        hhj_9->setObjectName(QString::fromUtf8("hhj_9"));
        hhj_9->setGeometry(QRect(450, 20, 121, 61));
        hhj_9->setFont(font1);
        hhj_10 = new QPushButton(haohuajian_2);
        hhj_10->setObjectName(QString::fromUtf8("hhj_10"));
        hhj_10->setGeometry(QRect(100, 100, 121, 61));
        hhj_10->setFont(font1);
        hhj_11 = new QPushButton(haohuajian_2);
        hhj_11->setObjectName(QString::fromUtf8("hhj_11"));
        hhj_11->setGeometry(QRect(450, 100, 121, 61));
        hhj_11->setFont(font1);
        hhj_12 = new QPushButton(haohuajian_2);
        hhj_12->setObjectName(QString::fromUtf8("hhj_12"));
        hhj_12->setGeometry(QRect(100, 180, 121, 61));
        hhj_12->setFont(font1);
        hhj_13 = new QPushButton(haohuajian_2);
        hhj_13->setObjectName(QString::fromUtf8("hhj_13"));
        hhj_13->setGeometry(QRect(450, 180, 121, 61));
        hhj_13->setFont(font1);
        hhj_14 = new QPushButton(haohuajian_2);
        hhj_14->setObjectName(QString::fromUtf8("hhj_14"));
        hhj_14->setGeometry(QRect(100, 260, 121, 61));
        hhj_14->setFont(font1);
        pushButton_9 = new QPushButton(haohuajian_2);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(450, 260, 121, 61));
        pushButton_9->setFont(font1);
        label_7 = new QLabel(haohuajian_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(1, 1, 721, 481));
        label_7->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget_2->addTab(haohuajian_2, QString());
        label_7->raise();
        hhj_8->raise();
        hhj_9->raise();
        hhj_10->raise();
        hhj_11->raise();
        hhj_12->raise();
        hhj_13->raise();
        hhj_14->raise();
        pushButton_9->raise();
        haohuataofang_2 = new QWidget();
        haohuataofang_2->setObjectName(QString::fromUtf8("haohuataofang_2"));
        hht_7 = new QPushButton(haohuataofang_2);
        hht_7->setObjectName(QString::fromUtf8("hht_7"));
        hht_7->setGeometry(QRect(100, 20, 121, 61));
        hht_7->setFont(font1);
        hht_8 = new QPushButton(haohuataofang_2);
        hht_8->setObjectName(QString::fromUtf8("hht_8"));
        hht_8->setGeometry(QRect(450, 20, 121, 61));
        hht_8->setFont(font1);
        hht_9 = new QPushButton(haohuataofang_2);
        hht_9->setObjectName(QString::fromUtf8("hht_9"));
        hht_9->setGeometry(QRect(100, 100, 121, 61));
        hht_9->setFont(font1);
        hht_10 = new QPushButton(haohuataofang_2);
        hht_10->setObjectName(QString::fromUtf8("hht_10"));
        hht_10->setGeometry(QRect(450, 100, 121, 61));
        hht_10->setFont(font1);
        hht_11 = new QPushButton(haohuataofang_2);
        hht_11->setObjectName(QString::fromUtf8("hht_11"));
        hht_11->setGeometry(QRect(100, 180, 121, 61));
        hht_11->setFont(font1);
        hht_12 = new QPushButton(haohuataofang_2);
        hht_12->setObjectName(QString::fromUtf8("hht_12"));
        hht_12->setGeometry(QRect(450, 180, 121, 61));
        hht_12->setFont(font1);
        label_8 = new QLabel(haohuataofang_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(1, 1, 721, 481));
        label_8->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget_2->addTab(haohuataofang_2, QString());
        label_8->raise();
        hht_7->raise();
        hht_8->raise();
        hht_9->raise();
        hht_10->raise();
        hht_11->raise();
        hht_12->raise();
        verticalTabWidget->addTab(verticalTabWidgetPage2, QString());
        verticalTabWidgetPage3 = new QWidget();
        verticalTabWidgetPage3->setObjectName(QString::fromUtf8("verticalTabWidgetPage3"));
        tabWidget_3 = new QTabWidget(verticalTabWidgetPage3);
        tabWidget_3->setObjectName(QString::fromUtf8("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(1, 1, 729, 519));
        tabWidget_3->setFont(font3);
        tabWidget_3->setStyleSheet(QString::fromUtf8(""));
        tabWidget_3->setTabPosition(QTabWidget::North);
        tabWidget_3->setTabShape(QTabWidget::Rounded);
        tabWidget_3->setElideMode(Qt::ElideNone);
        danrenjian_3 = new QWidget();
        danrenjian_3->setObjectName(QString::fromUtf8("danrenjian_3"));
        drj_21 = new QPushButton(danrenjian_3);
        drj_21->setObjectName(QString::fromUtf8("drj_21"));
        drj_21->setGeometry(QRect(450, 20, 120, 60));
        drj_21->setFont(font1);
        drj_22 = new QPushButton(danrenjian_3);
        drj_22->setObjectName(QString::fromUtf8("drj_22"));
        drj_22->setGeometry(QRect(100, 100, 120, 60));
        drj_22->setFont(font1);
        drj_23 = new QPushButton(danrenjian_3);
        drj_23->setObjectName(QString::fromUtf8("drj_23"));
        drj_23->setGeometry(QRect(100, 180, 120, 60));
        drj_23->setFont(font1);
        drj_24 = new QPushButton(danrenjian_3);
        drj_24->setObjectName(QString::fromUtf8("drj_24"));
        drj_24->setGeometry(QRect(450, 180, 120, 60));
        drj_24->setFont(font1);
        drj_25 = new QPushButton(danrenjian_3);
        drj_25->setObjectName(QString::fromUtf8("drj_25"));
        drj_25->setGeometry(QRect(100, 260, 120, 60));
        drj_25->setFont(font1);
        drj_26 = new QPushButton(danrenjian_3);
        drj_26->setObjectName(QString::fromUtf8("drj_26"));
        drj_26->setGeometry(QRect(450, 260, 120, 60));
        drj_26->setFont(font1);
        drj_27 = new QPushButton(danrenjian_3);
        drj_27->setObjectName(QString::fromUtf8("drj_27"));
        drj_27->setGeometry(QRect(100, 340, 120, 60));
        drj_27->setFont(font1);
        drj_28 = new QPushButton(danrenjian_3);
        drj_28->setObjectName(QString::fromUtf8("drj_28"));
        drj_28->setGeometry(QRect(100, 20, 120, 60));
        drj_28->setFont(font2);
        drj_29 = new QPushButton(danrenjian_3);
        drj_29->setObjectName(QString::fromUtf8("drj_29"));
        drj_29->setGeometry(QRect(450, 100, 120, 60));
        drj_29->setFont(font1);
        drj_30 = new QPushButton(danrenjian_3);
        drj_30->setObjectName(QString::fromUtf8("drj_30"));
        drj_30->setGeometry(QRect(450, 340, 120, 60));
        drj_30->setFont(font1);
        label_9 = new QLabel(danrenjian_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(0, 0, 721, 481));
        label_9->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget_3->addTab(danrenjian_3, QString());
        label_9->raise();
        drj_21->raise();
        drj_22->raise();
        drj_23->raise();
        drj_24->raise();
        drj_25->raise();
        drj_26->raise();
        drj_27->raise();
        drj_28->raise();
        drj_29->raise();
        drj_30->raise();
        shuangrenjian_3 = new QWidget();
        shuangrenjian_3->setObjectName(QString::fromUtf8("shuangrenjian_3"));
        srj_21 = new QPushButton(shuangrenjian_3);
        srj_21->setObjectName(QString::fromUtf8("srj_21"));
        srj_21->setGeometry(QRect(100, 20, 121, 61));
        srj_21->setFont(font1);
        srj_22 = new QPushButton(shuangrenjian_3);
        srj_22->setObjectName(QString::fromUtf8("srj_22"));
        srj_22->setGeometry(QRect(450, 20, 121, 61));
        srj_22->setFont(font1);
        srj_23 = new QPushButton(shuangrenjian_3);
        srj_23->setObjectName(QString::fromUtf8("srj_23"));
        srj_23->setGeometry(QRect(100, 100, 121, 61));
        srj_23->setFont(font1);
        srj_24 = new QPushButton(shuangrenjian_3);
        srj_24->setObjectName(QString::fromUtf8("srj_24"));
        srj_24->setGeometry(QRect(450, 100, 121, 61));
        srj_24->setFont(font1);
        srj_25 = new QPushButton(shuangrenjian_3);
        srj_25->setObjectName(QString::fromUtf8("srj_25"));
        srj_25->setGeometry(QRect(450, 180, 121, 61));
        srj_25->setFont(font1);
        srj_26 = new QPushButton(shuangrenjian_3);
        srj_26->setObjectName(QString::fromUtf8("srj_26"));
        srj_26->setGeometry(QRect(100, 260, 121, 61));
        srj_26->setFont(font1);
        srj_27 = new QPushButton(shuangrenjian_3);
        srj_27->setObjectName(QString::fromUtf8("srj_27"));
        srj_27->setGeometry(QRect(450, 260, 121, 61));
        srj_27->setFont(font1);
        srj_28 = new QPushButton(shuangrenjian_3);
        srj_28->setObjectName(QString::fromUtf8("srj_28"));
        srj_28->setGeometry(QRect(100, 180, 121, 61));
        srj_28->setFont(font1);
        srj_29 = new QPushButton(shuangrenjian_3);
        srj_29->setObjectName(QString::fromUtf8("srj_29"));
        srj_29->setGeometry(QRect(450, 340, 121, 61));
        srj_29->setFont(font1);
        srj_30 = new QPushButton(shuangrenjian_3);
        srj_30->setObjectName(QString::fromUtf8("srj_30"));
        srj_30->setGeometry(QRect(100, 340, 121, 61));
        srj_30->setFont(font1);
        label_10 = new QLabel(shuangrenjian_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(0, 0, 721, 481));
        label_10->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget_3->addTab(shuangrenjian_3, QString());
        label_10->raise();
        srj_21->raise();
        srj_22->raise();
        srj_23->raise();
        srj_24->raise();
        srj_25->raise();
        srj_26->raise();
        srj_27->raise();
        srj_28->raise();
        srj_29->raise();
        srj_30->raise();
        haohuajian_3 = new QWidget();
        haohuajian_3->setObjectName(QString::fromUtf8("haohuajian_3"));
        hhj_15 = new QPushButton(haohuajian_3);
        hhj_15->setObjectName(QString::fromUtf8("hhj_15"));
        hhj_15->setGeometry(QRect(100, 20, 121, 61));
        hhj_15->setFont(font1);
        hhj_16 = new QPushButton(haohuajian_3);
        hhj_16->setObjectName(QString::fromUtf8("hhj_16"));
        hhj_16->setGeometry(QRect(450, 20, 121, 61));
        hhj_16->setFont(font1);
        hhj_17 = new QPushButton(haohuajian_3);
        hhj_17->setObjectName(QString::fromUtf8("hhj_17"));
        hhj_17->setGeometry(QRect(100, 100, 121, 61));
        hhj_17->setFont(font1);
        hhj_18 = new QPushButton(haohuajian_3);
        hhj_18->setObjectName(QString::fromUtf8("hhj_18"));
        hhj_18->setGeometry(QRect(450, 100, 121, 61));
        hhj_18->setFont(font1);
        hhj_19 = new QPushButton(haohuajian_3);
        hhj_19->setObjectName(QString::fromUtf8("hhj_19"));
        hhj_19->setGeometry(QRect(100, 180, 121, 61));
        hhj_19->setFont(font1);
        hhj_20 = new QPushButton(haohuajian_3);
        hhj_20->setObjectName(QString::fromUtf8("hhj_20"));
        hhj_20->setGeometry(QRect(450, 180, 121, 61));
        hhj_20->setFont(font1);
        hhj_21 = new QPushButton(haohuajian_3);
        hhj_21->setObjectName(QString::fromUtf8("hhj_21"));
        hhj_21->setGeometry(QRect(100, 260, 121, 61));
        hhj_21->setFont(font1);
        pushButton_10 = new QPushButton(haohuajian_3);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(450, 260, 121, 61));
        pushButton_10->setFont(font1);
        label_11 = new QLabel(haohuajian_3);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(1, 1, 721, 481));
        label_11->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget_3->addTab(haohuajian_3, QString());
        label_11->raise();
        hhj_15->raise();
        hhj_16->raise();
        hhj_17->raise();
        hhj_18->raise();
        hhj_19->raise();
        hhj_20->raise();
        hhj_21->raise();
        pushButton_10->raise();
        haohuataofang_3 = new QWidget();
        haohuataofang_3->setObjectName(QString::fromUtf8("haohuataofang_3"));
        hht_13 = new QPushButton(haohuataofang_3);
        hht_13->setObjectName(QString::fromUtf8("hht_13"));
        hht_13->setGeometry(QRect(100, 20, 121, 61));
        hht_13->setFont(font1);
        hht_14 = new QPushButton(haohuataofang_3);
        hht_14->setObjectName(QString::fromUtf8("hht_14"));
        hht_14->setGeometry(QRect(450, 20, 121, 61));
        hht_14->setFont(font1);
        hht_15 = new QPushButton(haohuataofang_3);
        hht_15->setObjectName(QString::fromUtf8("hht_15"));
        hht_15->setGeometry(QRect(100, 100, 121, 61));
        hht_15->setFont(font1);
        hht_16 = new QPushButton(haohuataofang_3);
        hht_16->setObjectName(QString::fromUtf8("hht_16"));
        hht_16->setGeometry(QRect(450, 100, 121, 61));
        hht_16->setFont(font1);
        hht_17 = new QPushButton(haohuataofang_3);
        hht_17->setObjectName(QString::fromUtf8("hht_17"));
        hht_17->setGeometry(QRect(100, 180, 121, 61));
        hht_17->setFont(font1);
        hht_18 = new QPushButton(haohuataofang_3);
        hht_18->setObjectName(QString::fromUtf8("hht_18"));
        hht_18->setGeometry(QRect(450, 180, 121, 61));
        hht_18->setFont(font1);
        label_12 = new QLabel(haohuataofang_3);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(0, 0, 721, 481));
        label_12->setStyleSheet(QString::fromUtf8("border-image: url(:/picture/1.jpg);"));
        tabWidget_3->addTab(haohuataofang_3, QString());
        label_12->raise();
        hht_13->raise();
        hht_14->raise();
        hht_15->raise();
        hht_16->raise();
        hht_17->raise();
        hht_18->raise();
        verticalTabWidget->addTab(verticalTabWidgetPage3, QString());

        gridLayout_3->addWidget(verticalTabWidget, 0, 0, 1, 1);


        retranslateUi(Dialog);

        verticalTabWidget->setCurrentIndex(2);
        tabWidget->setCurrentIndex(3);
        tabWidget_2->setCurrentIndex(3);
        tabWidget_3->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QApplication::translate("Dialog", "Dialog", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        Dialog->setToolTip(QApplication::translate("Dialog", "<html><head/><body><p>\346\214\211\345\247\223\345\220\215\346\237\245\350\257\242</p></body></html>", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_TOOLTIP
        verticalTabWidget->setToolTip(QApplication::translate("Dialog", "\345\205\245\344\275\217", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_WHATSTHIS
        verticalTabWidget->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
#ifndef QT_NO_TOOLTIP
        tabWidget->setToolTip(QApplication::translate("Dialog", "<html><head/><body><p>\345\215\225\344\272\272\351\227\264</p></body></html>", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_TOOLTIP
        drj_2->setToolTip(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        drj_2->setText(QApplication::translate("Dialog", "102", 0, QApplication::UnicodeUTF8));
        drj_3->setText(QApplication::translate("Dialog", "103", 0, QApplication::UnicodeUTF8));
        drj_5->setText(QApplication::translate("Dialog", "105", 0, QApplication::UnicodeUTF8));
        drj_6->setText(QApplication::translate("Dialog", "106", 0, QApplication::UnicodeUTF8));
        drj_7->setText(QApplication::translate("Dialog", "107", 0, QApplication::UnicodeUTF8));
        drj_8->setText(QApplication::translate("Dialog", "108", 0, QApplication::UnicodeUTF8));
        drj_9->setText(QApplication::translate("Dialog", "109", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        drj_1->setToolTip(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        drj_1->setText(QApplication::translate("Dialog", "101", 0, QApplication::UnicodeUTF8));
        drj_4->setText(QApplication::translate("Dialog", "104", 0, QApplication::UnicodeUTF8));
        drj_10->setText(QApplication::translate("Dialog", "110", 0, QApplication::UnicodeUTF8));
        label->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(danrenjian), QApplication::translate("Dialog", "\345\215\225\344\272\272\351\227\264", 0, QApplication::UnicodeUTF8));
        srj_1->setText(QApplication::translate("Dialog", "201", 0, QApplication::UnicodeUTF8));
        srj_2->setText(QApplication::translate("Dialog", "202", 0, QApplication::UnicodeUTF8));
        srj_3->setText(QApplication::translate("Dialog", "203", 0, QApplication::UnicodeUTF8));
        srj_4->setText(QApplication::translate("Dialog", "204", 0, QApplication::UnicodeUTF8));
        srj_6->setText(QApplication::translate("Dialog", "206", 0, QApplication::UnicodeUTF8));
        srj_7->setText(QApplication::translate("Dialog", "207", 0, QApplication::UnicodeUTF8));
        srj_8->setText(QApplication::translate("Dialog", "208", 0, QApplication::UnicodeUTF8));
        srj_5->setText(QApplication::translate("Dialog", "205", 0, QApplication::UnicodeUTF8));
        srj_10->setText(QApplication::translate("Dialog", "210", 0, QApplication::UnicodeUTF8));
        srj_9->setText(QApplication::translate("Dialog", "209", 0, QApplication::UnicodeUTF8));
        label_2->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(shuangrenjian), QApplication::translate("Dialog", "\345\217\214\344\272\272\351\227\264", 0, QApplication::UnicodeUTF8));
        hhj_1->setText(QApplication::translate("Dialog", "301", 0, QApplication::UnicodeUTF8));
        hhj_2->setText(QApplication::translate("Dialog", "302", 0, QApplication::UnicodeUTF8));
        hhj_3->setText(QApplication::translate("Dialog", "303", 0, QApplication::UnicodeUTF8));
        hhj_4->setText(QApplication::translate("Dialog", "304", 0, QApplication::UnicodeUTF8));
        hhj_5->setText(QApplication::translate("Dialog", "305", 0, QApplication::UnicodeUTF8));
        hhj_6->setText(QApplication::translate("Dialog", "306", 0, QApplication::UnicodeUTF8));
        hhj_7->setText(QApplication::translate("Dialog", "307", 0, QApplication::UnicodeUTF8));
        pushButton_8->setText(QApplication::translate("Dialog", "308", 0, QApplication::UnicodeUTF8));
        label_3->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(haohuajian), QApplication::translate("Dialog", "\350\261\252\345\215\216\351\227\264", 0, QApplication::UnicodeUTF8));
        hht_1->setText(QApplication::translate("Dialog", "401", 0, QApplication::UnicodeUTF8));
        hht_2->setText(QApplication::translate("Dialog", "402", 0, QApplication::UnicodeUTF8));
        hht_3->setText(QApplication::translate("Dialog", "403", 0, QApplication::UnicodeUTF8));
        hht_4->setText(QApplication::translate("Dialog", "404", 0, QApplication::UnicodeUTF8));
        hht_5->setText(QApplication::translate("Dialog", "405", 0, QApplication::UnicodeUTF8));
        hht_6->setText(QApplication::translate("Dialog", "406", 0, QApplication::UnicodeUTF8));
        label_4->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(haohuataofang), QApplication::translate("Dialog", "\350\261\252\345\215\216\345\245\227\346\210\277", 0, QApplication::UnicodeUTF8));
        verticalTabWidget->setTabText(verticalTabWidget->indexOf(verticalTabWidgetPage1), QApplication::translate("Dialog", "\345\205\245\344\275\217", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        tabWidget_2->setToolTip(QApplication::translate("Dialog", "<html><head/><body><p>\345\215\225\344\272\272\351\227\264</p></body></html>", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_TOOLTIP
        drj_11->setToolTip(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        drj_11->setText(QApplication::translate("Dialog", "102", 0, QApplication::UnicodeUTF8));
        drj_12->setText(QApplication::translate("Dialog", "103", 0, QApplication::UnicodeUTF8));
        drj_13->setText(QApplication::translate("Dialog", "105", 0, QApplication::UnicodeUTF8));
        drj_14->setText(QApplication::translate("Dialog", "106", 0, QApplication::UnicodeUTF8));
        drj_15->setText(QApplication::translate("Dialog", "107", 0, QApplication::UnicodeUTF8));
        drj_16->setText(QApplication::translate("Dialog", "108", 0, QApplication::UnicodeUTF8));
        drj_17->setText(QApplication::translate("Dialog", "109", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        drj_18->setToolTip(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        drj_18->setText(QApplication::translate("Dialog", "101", 0, QApplication::UnicodeUTF8));
        drj_19->setText(QApplication::translate("Dialog", "104", 0, QApplication::UnicodeUTF8));
        drj_20->setText(QApplication::translate("Dialog", "110", 0, QApplication::UnicodeUTF8));
        label_5->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(danrenjian_2), QApplication::translate("Dialog", "\345\215\225\344\272\272\351\227\264", 0, QApplication::UnicodeUTF8));
        srj_11->setText(QApplication::translate("Dialog", "201", 0, QApplication::UnicodeUTF8));
        srj_12->setText(QApplication::translate("Dialog", "202", 0, QApplication::UnicodeUTF8));
        srj_13->setText(QApplication::translate("Dialog", "203", 0, QApplication::UnicodeUTF8));
        srj_14->setText(QApplication::translate("Dialog", "204", 0, QApplication::UnicodeUTF8));
        srj_15->setText(QApplication::translate("Dialog", "206", 0, QApplication::UnicodeUTF8));
        srj_16->setText(QApplication::translate("Dialog", "207", 0, QApplication::UnicodeUTF8));
        srj_17->setText(QApplication::translate("Dialog", "208", 0, QApplication::UnicodeUTF8));
        srj_18->setText(QApplication::translate("Dialog", "205", 0, QApplication::UnicodeUTF8));
        srj_19->setText(QApplication::translate("Dialog", "210", 0, QApplication::UnicodeUTF8));
        srj_20->setText(QApplication::translate("Dialog", "209", 0, QApplication::UnicodeUTF8));
        label_6->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(shuangrenjian_2), QApplication::translate("Dialog", "\345\217\214\344\272\272\351\227\264", 0, QApplication::UnicodeUTF8));
        hhj_8->setText(QApplication::translate("Dialog", "301", 0, QApplication::UnicodeUTF8));
        hhj_9->setText(QApplication::translate("Dialog", "302", 0, QApplication::UnicodeUTF8));
        hhj_10->setText(QApplication::translate("Dialog", "303", 0, QApplication::UnicodeUTF8));
        hhj_11->setText(QApplication::translate("Dialog", "304", 0, QApplication::UnicodeUTF8));
        hhj_12->setText(QApplication::translate("Dialog", "305", 0, QApplication::UnicodeUTF8));
        hhj_13->setText(QApplication::translate("Dialog", "306", 0, QApplication::UnicodeUTF8));
        hhj_14->setText(QApplication::translate("Dialog", "307", 0, QApplication::UnicodeUTF8));
        pushButton_9->setText(QApplication::translate("Dialog", "308", 0, QApplication::UnicodeUTF8));
        label_7->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(haohuajian_2), QApplication::translate("Dialog", "\350\261\252\345\215\216\351\227\264", 0, QApplication::UnicodeUTF8));
        hht_7->setText(QApplication::translate("Dialog", "401", 0, QApplication::UnicodeUTF8));
        hht_8->setText(QApplication::translate("Dialog", "402", 0, QApplication::UnicodeUTF8));
        hht_9->setText(QApplication::translate("Dialog", "403", 0, QApplication::UnicodeUTF8));
        hht_10->setText(QApplication::translate("Dialog", "404", 0, QApplication::UnicodeUTF8));
        hht_11->setText(QApplication::translate("Dialog", "405", 0, QApplication::UnicodeUTF8));
        hht_12->setText(QApplication::translate("Dialog", "406", 0, QApplication::UnicodeUTF8));
        label_8->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(haohuataofang_2), QApplication::translate("Dialog", "\350\261\252\345\215\216\345\245\227\346\210\277", 0, QApplication::UnicodeUTF8));
        verticalTabWidget->setTabText(verticalTabWidget->indexOf(verticalTabWidgetPage2), QApplication::translate("Dialog", "\351\242\204\345\256\232", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        tabWidget_3->setToolTip(QApplication::translate("Dialog", "<html><head/><body><p>\345\215\225\344\272\272\351\227\264</p></body></html>", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_TOOLTIP
        drj_21->setToolTip(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        drj_21->setText(QApplication::translate("Dialog", "102", 0, QApplication::UnicodeUTF8));
        drj_22->setText(QApplication::translate("Dialog", "103", 0, QApplication::UnicodeUTF8));
        drj_23->setText(QApplication::translate("Dialog", "105", 0, QApplication::UnicodeUTF8));
        drj_24->setText(QApplication::translate("Dialog", "106", 0, QApplication::UnicodeUTF8));
        drj_25->setText(QApplication::translate("Dialog", "107", 0, QApplication::UnicodeUTF8));
        drj_26->setText(QApplication::translate("Dialog", "108", 0, QApplication::UnicodeUTF8));
        drj_27->setText(QApplication::translate("Dialog", "109", 0, QApplication::UnicodeUTF8));
#ifndef QT_NO_TOOLTIP
        drj_28->setToolTip(QApplication::translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>", 0, QApplication::UnicodeUTF8));
#endif // QT_NO_TOOLTIP
        drj_28->setText(QApplication::translate("Dialog", "101", 0, QApplication::UnicodeUTF8));
        drj_29->setText(QApplication::translate("Dialog", "104", 0, QApplication::UnicodeUTF8));
        drj_30->setText(QApplication::translate("Dialog", "110", 0, QApplication::UnicodeUTF8));
        label_9->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(danrenjian_3), QApplication::translate("Dialog", "\345\215\225\344\272\272\351\227\264", 0, QApplication::UnicodeUTF8));
        srj_21->setText(QApplication::translate("Dialog", "201", 0, QApplication::UnicodeUTF8));
        srj_22->setText(QApplication::translate("Dialog", "202", 0, QApplication::UnicodeUTF8));
        srj_23->setText(QApplication::translate("Dialog", "203", 0, QApplication::UnicodeUTF8));
        srj_24->setText(QApplication::translate("Dialog", "204", 0, QApplication::UnicodeUTF8));
        srj_25->setText(QApplication::translate("Dialog", "206", 0, QApplication::UnicodeUTF8));
        srj_26->setText(QApplication::translate("Dialog", "207", 0, QApplication::UnicodeUTF8));
        srj_27->setText(QApplication::translate("Dialog", "208", 0, QApplication::UnicodeUTF8));
        srj_28->setText(QApplication::translate("Dialog", "205", 0, QApplication::UnicodeUTF8));
        srj_29->setText(QApplication::translate("Dialog", "210", 0, QApplication::UnicodeUTF8));
        srj_30->setText(QApplication::translate("Dialog", "209", 0, QApplication::UnicodeUTF8));
        label_10->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(shuangrenjian_3), QApplication::translate("Dialog", "\345\217\214\344\272\272\351\227\264", 0, QApplication::UnicodeUTF8));
        hhj_15->setText(QApplication::translate("Dialog", "301", 0, QApplication::UnicodeUTF8));
        hhj_16->setText(QApplication::translate("Dialog", "302", 0, QApplication::UnicodeUTF8));
        hhj_17->setText(QApplication::translate("Dialog", "303", 0, QApplication::UnicodeUTF8));
        hhj_18->setText(QApplication::translate("Dialog", "304", 0, QApplication::UnicodeUTF8));
        hhj_19->setText(QApplication::translate("Dialog", "305", 0, QApplication::UnicodeUTF8));
        hhj_20->setText(QApplication::translate("Dialog", "306", 0, QApplication::UnicodeUTF8));
        hhj_21->setText(QApplication::translate("Dialog", "307", 0, QApplication::UnicodeUTF8));
        pushButton_10->setText(QApplication::translate("Dialog", "308", 0, QApplication::UnicodeUTF8));
        label_11->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(haohuajian_3), QApplication::translate("Dialog", "\350\261\252\345\215\216\351\227\264", 0, QApplication::UnicodeUTF8));
        hht_13->setText(QApplication::translate("Dialog", "401", 0, QApplication::UnicodeUTF8));
        hht_14->setText(QApplication::translate("Dialog", "402", 0, QApplication::UnicodeUTF8));
        hht_15->setText(QApplication::translate("Dialog", "403", 0, QApplication::UnicodeUTF8));
        hht_16->setText(QApplication::translate("Dialog", "404", 0, QApplication::UnicodeUTF8));
        hht_17->setText(QApplication::translate("Dialog", "405", 0, QApplication::UnicodeUTF8));
        hht_18->setText(QApplication::translate("Dialog", "406", 0, QApplication::UnicodeUTF8));
        label_12->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(haohuataofang_3), QApplication::translate("Dialog", "\350\261\252\345\215\216\345\245\227\346\210\277", 0, QApplication::UnicodeUTF8));
        verticalTabWidget->setTabText(verticalTabWidget->indexOf(verticalTabWidgetPage3), QApplication::translate("Dialog", "\351\200\200\346\210\277", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_NEWG_H
